### ISSUE TITLE
Another Test

### ISSUE THREAD

**Issue by nicholaschiasson** [nicholaschiasson/nicholaschiasson.github.io#10]
# The second test issue
This blog post is **exciting**!!!

**Comment by nicholaschiasson** [comment]
Yet another comment on another test.

**Comment by nicholaschiasson** [comment]
Test comment from site

**Comment by nicholaschiasson** [comment]
One more for the show

**Comment by nicholaschiasson** [comment]
Hello self updating comments section!

**Comment by nicholaschiasson** [comment]
will 'this' break it?

**Comment by nicholaschiasson** [comment]
hi

**Comment by nicholaschiasson** [comment]
plis

**Comment by nicholaschiasson** [comment]
hello

**Comment by nicholaschiasson** [comment]
ok?

**Comment by nicholaschiasson** [comment]
Okay, show em comments.

**Comment by nicholaschiasson** [comment]
It is working!!!

**Comment by nicholaschiasson** [comment]
Okay, maybe not?

**Comment by nicholaschiasson** [comment]
Show me the comments

**Comment by nicholaschiasson** [comment]
WHY

**Comment by nicholaschiasson** [comment]
Testing the no cache update.

**Comment by nicholaschiasson** [comment]
Okay, seems to work, here goes another.

**Comment by nicholaschiasson** [comment]
NICE! I have figured it out!

**Comment by nicholaschiasson** [comment]
Comment testing.

**Comment by nicholaschiasson** [comment]
Another test.

**Comment by nicholaschiasson** [comment]
# First entry!


Hi! My name is Nick and this is the first entry into my personal website's blog.
The significance of this event is not so much the birth of the blog itself, but
the accomplishment of developing the blog system. I had the idea to make use of
Github Pages to make a very simple blog system in which updates could be made by
simply pushing new markdown files to the repository. I saw this as a nice little
challenge considering Github Pages doesn't support hosting real web apps, but
only static HTML pages. Thus, my hacking was very experimental and purely a
learning experience. Nevertheless, from the experience also came a little place
I could call my own on the internet -- a place into which I could post whatever
I felt like. So here is to a future of untold adventures.

## Some things

- a thing
- another thing

### Okay some other things

1. Big thing
2. Little thing
3. Small thing

##### Last thing

- [ ] Checky thing
- [x] Checked thing
- [ ] Unchecked thing

###### And now for some code

```let x = 2;```

A paragraph again.

```
// and now for a block of code
#include <stdio.h>

int main(int argc, char *argv[])
{
  println("Hello, world!\n");
  return 0;
}
```

Cheers!

**Comment by nicholaschiasson** [comment]
Test comment while logged out of github.

**Comment by nickytest** [comment]
Hi guys, I'm new here and I wanted to help you test.

### How is this?

**Comment by nickytest** [comment]
This is a comment that I'm going to delete

**Comment by nickytest** [comment]
Signed into the other github account, but still nickytest here it seems. I think that's okay though, nobody really has two github accounts do they..?

**Comment by nicholaschiasson** [comment]
It's me again :)

**Comment by nicholaschiasson** [comment]
@nickytest Let's see if tagging works.
How about referencing another issue, like this one #11
